# Generated by Django 5.0.6 on 2025-04-07 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_game_moves_alter_game_winner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='player_black_id',
            new_name='player_black',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player_white_id',
            new_name='player_white',
        ),
        migrations.RemoveField(
            model_name='game',
            name='moves',
        ),
        migrations.AddField(
            model_name='move',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='api.game'),
            preserve_default=False,
        ),
    ]
