# Generated by Django 5.0.6 on 2025-04-09 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_game_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='board_state',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='game',
            name='current_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_turn_games', to='api.user'),
        ),
        migrations.AddField(
            model_name='game',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
