version: "3.9"

services:
  backend:
    build: ./backend
    command: daphne -b 0.0.0.0 -p 8000 core.asgi:application
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: vite-app
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: Postgres
      POSTGRES_PASSWORD: 2015karl
      POSTGRES_DB: ChessDB
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  pg_data: