# Generated by Django 5.0.6 on 2025-03-27 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('move', models.CharField(max_length=10)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('avatar_img', models.ImageField(upload_to='avatars/')),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('CM', 'Checkmate'), ('SM', 'Stalemate'), ('DW', 'Draw'), ('PPC', 'Perpetual check'), ('ISFCM', 'Insufficient material'), ('TFRP', 'Threefold repetition'), ('FMR', 'Fifty-move rule')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_moves', to='api.move')),
                ('player_black_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_games', to='api.user')),
                ('player_white_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_games', to='api.user')),
                ('winner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='win_games', to='api.user')),
            ],
        ),
    ]
